title: Jan Tobola
description: I am Jan Tobola and this is my personal blog about programming and interesting things from programming world I've had to deal with...

url: http://jantobola.com
baseurl: ""
paginate_path: "blog/page/:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Blog
   url: /blog
 - title: About Me
   url: /
 - title: Contact
   url: /contact

homepage:
    navigation_name: About Me
    route_alias: /about/

social:
   github: Toby91
   twitter: JanTobola
   facebook: honza.tobola
   email: tobola.jan@gmail.com

google_analytics: "UA-86413564-1"